# Generated by Django 4.1.7 on 2023-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('edad', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=250)),
                ('codigo_postal', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=350)),
                ('direccion', models.CharField(max_length=250)),
                ('persona', models.ManyToManyField(related_name='direcciones', to='libreta.persona')),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': 'direcciones',
            },
        ),
    ]
